// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdBaLV2pbWectxK7Ao5WvIRfjWEHUt61I',
    appId: '1:292361302156:web:b3dea5bbf1813dbfd78ba9',
    messagingSenderId: '292361302156',
    projectId: 'authtestappignis',
    authDomain: 'authtestappignis.firebaseapp.com',
    storageBucket: 'authtestappignis.appspot.com',
    measurementId: 'G-33R8RF7F3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCrl4aHb99VvRHVASrRpD4w5RZmboFOwE',
    appId: '1:292361302156:android:bf71d072bb648905d78ba9',
    messagingSenderId: '292361302156',
    projectId: 'authtestappignis',
    storageBucket: 'authtestappignis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKGBU7yFzoCoc5KFVnw7tXrbY74X1kGjs',
    appId: '1:292361302156:ios:c7bf41bb0832b934d78ba9',
    messagingSenderId: '292361302156',
    projectId: 'authtestappignis',
    storageBucket: 'authtestappignis.appspot.com',
    iosClientId: '292361302156-ei1mv7pl6uboinepbpu9t6ta5h95j29r.apps.googleusercontent.com',
    iosBundleId: 'com.ignisideas.authtestappignis',
  );
}
